# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-7.12

# User packages to be built.
packages:
- '.'
- '../aira-bot-platform'
- '../telegram-bot'
- '../web3'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- telegram-api-0.5.0.1
- aeson-1.0.2.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
